version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
    timezone: America/New_York
  open-pull-requests-limit: 10
  target-branch: master
