version: 1
update_configs:
  - package_manager: "dotnet:nuget"
    directory: "/"
    update_schedule: "live"
    target_branch: "develop"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"